### ISSUE TITLE
Import using NPM on React project issuing errors

### ISSUE THREAD

**Issue by pccassin** [opentok/opentok-react#104]
Hello, 

I was trying to implement opentok on a React simple app and decided to test your component. But when importing it I've received those errors:

`pcassin@NI-42232-2:/mnt/c/Users/pcassin/Documents/GitHub/medlink/medlink$ sudo npm install --save opentok-react
loadExtraneous            ▄ ╢██████████████████████████░░░░░░░░░░░░░░░░░░░░░╟
WARN engine fsevents@2.1.2: wanted: {"node":"^8.16.0 || ^10.6.0 || >=11.0.0"} loadDep:fsevents          ▀ ╢█████████████████████████░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine fsevents@2.1.2: wanted: {"node":"^8.16.0 || ^10.6.0 || >=11.0.0"} medlink@0.1.0 /mnt/c/Users/pcassin/Documents/GitHub/medlink/medlink
├── opentok-react@0.10.0 
├── UNMET DEPENDENCY react@^16.13.1
├── react-dom@16.13.1 
├─┬ react-scripts@3.4.1 
│ ├── UNMET PEER DEPENDENCY fibers@>= 3.1.0
│ ├── UNMET PEER DEPENDENCY node-sass@^4.0.0
│ └── UNMET PEER DEPENDENCY sass@^1.3.0
└── UNMET PEER DEPENDENCY typescript@^3.2.1

npm WARN optional Skipping failed optional dependency /jest-haste-map/fsevents
:
npm WARN notsup Not compatible with your operating system or architecture: fse
vents@1.2.12
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fse
vents@2.1.2
npm WARN optional Skipping failed optional dependency /react-scripts/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fse
vents@2.1.2
npm WARN optional Skipping failed optional dependency /watchpack/chokidar/fsev
ents:
npm WARN notsup Not compatible with your operating system or architecture: fse
vents@1.2.12
npm WARN optional Skipping failed optional dependency /webpack-dev-server/chok
idar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fse
vents@1.2.12
npm WARN react-scripts@3.4.1 requires a peer of typescript@^3.2.1 but none was
 installed.
npm WARN sass-loader@8.0.2 requires a peer of node-sass@^4.0.0 but none was in
stalled.
npm WARN sass-loader@8.0.2 requires a peer of sass@^1.3.0 but none was install
ed.
npm WARN sass-loader@8.0.2 requires a peer of fibers@>= 3.1.0 but none was ins
talled.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev 
|| >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none was installed.
npm ERR! Linux 4.4.0-17134-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "opentok-react"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /mnt/c/Users/pcassin/Documents/GitHub/medlink/medlink/node_modules/react
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rename

npm ERR! Error: EACCES: permission denied, rename '/mnt/c/Users/pcassin/Documents/GitHub/medlink/medlink/node_modules/react' -> '/mnt/c/Users/pcassin/Documents/GitHub/medlink/medlink/node_modules/.react.DELETE'
npm ERR!     at moveAway (/usr/share/npm/lib/install/action/finalize.js:38:5)
npm ERR!     at destStatted (/usr/share/npm/lib/install/action/finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:153:5)
npm ERR! 
npm ERR! Error: EACCES: permission denied, rename '/mnt/c/Users/pcassin/Documents/GitHub/medlink/medlink/node_modules/react' -> '/mnt/c/Users/pcassin/Documents/GitHub/medlink/medlink/node_modules/.react.DELETE'
npm ERR!  { Error: EACCES: permission denied, rename '/mnt/c/Users/pcassin/Documents/GitHub/medlink/medlink/node_modules/react' -> '/mnt/c/Users/pcassin/Documents/GitHub/medlink/medlink/node_modules/.react.DELETE'
npm ERR!     at moveAway (/usr/share/npm/lib/install/action/finalize.js:38:5)
npm ERR!     at destStatted (/usr/share/npm/lib/install/action/finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:153:5)
npm ERR! 
npm ERR! Error: EACCES: permission denied, rename '/mnt/c/Users/pcassin/Documents/GitHub/medlink/medlink/node_modules/react' -> '/mnt/c/Users/pcassin/Documents/GitHub/medlink/medlink/node_modules/.react.DELETE' parent: 'medlink' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/pcassin/Documents/GitHub/medlink/medlink/npm-debug.log`

Its my first app in react, after a bunch of tutorials, so if you help me understand what's going on, should be amazing!

**Comment by pccassin** [comment]
Issue Resolved - I've forgot to install all dependencies using "npm install".
